import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");
const cargoToml = resolve(rootDir, "wasm/stft/Cargo.toml");
const wasmOut = resolve(
  rootDir,
  "wasm/stft/target/wasm32-unknown-unknown/release/stft_wasm.wasm",
);
const targetTs = resolve(
  rootDir,
  "packages/core/src/backends/wasm-stft-binary.ts",
);

console.log("[build-wasm] Building Rust crate to wasm32-unknown-unknown...");
execSync(
  `cargo build --manifest-path "${cargoToml}" --target wasm32-unknown-unknown --release`,
  {
    stdio: "inherit",
  },
);

const wasmBuffer = readFileSync(wasmOut);
const base64 = wasmBuffer.toString("base64");

console.log(
  `[build-wasm] WASM binary size: ${wasmBuffer.length} bytes (base64 length: ${base64.length})`,
);

const tsContent = `// Auto-generated by scripts/build-wasm.mjs - DO NOT EDIT MANUALLY
export const WASM_STFT_BASE64: string = "${base64}";

export function getWasmStftBinary(): Uint8Array {
  const g = globalThis as {
    Buffer?: { from(str: string, enc: string): Uint8Array };
    atob?: (str: string) => string;
  };
  if (g.Buffer) {
    return new Uint8Array(g.Buffer.from(WASM_STFT_BASE64, "base64"));
  }
  if (g.atob) {
    const binaryString = g.atob(WASM_STFT_BASE64);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    return bytes;
  }
  throw new Error("Neither Buffer nor atob is available in this environment.");
}
`;

writeFileSync(targetTs, tsContent, "utf8");
console.log(`[build-wasm] Wrote ${targetTs}`);
