export const version = '0.0.0';
export { MainThreadComputeBackend } from './backend';
export type { ComputeTileRequest, SpectrogramComputeBackend } from './backend';
export { createTileKey, SpectrogramCache } from './cache';
export type { TileKeyParts } from './cache';
export { buildColorMap, parseColor } from './colormap';
export { resolveConfig, stableHash } from './config';
export { TypedEventEmitter } from './events';
export { canvasToTimeFrequency, hzToMel, hzToScale, melToHz, scaleToHz, timeFrequencyToCanvas } from './frequency-scale';
export { CanvasSpectrogramRenderer, pickNearestBin, pickNearestFrame } from './renderer';
export type { RenderInput } from './renderer';
export { DecodedAudioSource } from './source';
export { computeStftMatrix, createWindow } from './stft';
export { applyTransforms, getTransformPadding } from './transforms';
export { dbFromMagnitude, deriveDb, derivePower, deriveValueArrays, normalizeValue } from './value-scale';
export { SpectrogramViewer } from './viewer';
export type * from './types';
